name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  nix:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)
    uses: hyprwm/actions/.github/workflows/nix.yml@main
    secrets: inherit
    with:
      submodules: recursive
      command: nix build --print-build-logs --accept-flake-config
